### ISSUE TITLE
Why I can not see the dynamic result

### ISSUE THREAD

**Issue by databill** [tex/vimpreviewpandoc#1]
Before I find this plugin, I use vim-markdown. It does not support diag tools. Thanks a lot for this dramatic tool to write the markdown files. 

I do exactly as the introduction guides.
Vim Plugin Setup link this

``` vimrc
Plugin 'vim-pandoc/vim-pantondoc'                                                
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'vim-pandoc/vim-pandoc-after'
Plugin 'tex/vimpreviewpandoc'
...
autocmd BufNewFile,BufRead *.md set filetype=pandoc
```

System information:
- OSX 10.10.4
- Python 2.7
- Tools like blockdiag, seqdiag, actdiag, nwdiag, packetdiag, rackdiag have been installed, and I can produce these png file in cli
- Dependencies like pandocfilters, six have been installed
### Issue#1

``````
    ```nwdiag                                                                           
 nwdiag{
     network dmz {
         address = "210.x.x.x/24"
         web01 [address = "210.x.x.1"];
         web02 [address = "210.x.x.2"];
         }   
     network internal {
         address = "172.x.x.x/24";
         web01 [address = "172.x.x.1"];
         web02 [address = "172.x.x.2"];
         db01;
         db02;
         }   
 }
    ```
``````

The localhost:8090 looks like this

```
nwdiag{
    network dmz {
        address = "210.x.x.x/24"
        web01 [address = "210.x.x.1"];
        web02 [address = "210.x.x.2"];
        }
    network internal {
        address = "172.x.x.x/24";
        web01 [address = "172.x.x.1"];
        web02 [address = "172.x.x.2"];
        db01;
        db02;
        }
}
```

no png will be shown but text.

In the mardown file current path, I can see that **a .dot path and the xxxx.png files** have been produced. Why these file are not be replaced in the browser view?
### Issue#2

When I open a md file, I find that this function VimPreviewPandocConvertTo does not exist

```
:call VimPreviewPandocConvertTo("docx,html")
```

**Comment by tex** [comment]
If it generated a png files that problem must be with paths... Can you use tools in Firefox (I'm assuming you are using Fireefox) to see what paths suppoesed images have? The images should still be present in preview in its DOM.

**Comment by tex** [comment]
Issue#2: wrong doc, thanks, I updated that.

**Comment by databill** [comment]
hi tex,

Yea, I do use Firefox. 
Can you show me how to view the paths? I only can see that Firefox open a socket to get the data. The source code of the page is very simple.
I can not see "http get xxx.png" call in the trace either.

```
<!DOCTYPE html>
<html lang="en" class="">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Language" content="en">
  <link rel="stylesheet" type="text/css" href="/github-syntax-highlight.css">
  <link rel="stylesheet" type="text/css" href="/github-markdown.css">
  <style>
    .markdown-body {
      min-width: 200px;
      max-width: 790px;
      margin: 0 auto;
      padding: 30px;
    }
  </style>
  <script src="/socket.io/socket.io.js"></script>
  <script>
    var socket = io.connect('http://localhost:8090/');
    socket.on('connect', function () {
      socket.on('newContent', function(newHTML) {
        document.querySelector(".markdown-body").innerHTML = newHTML;
      });
      socket.on('die', function(newHTML) {
        window.open('', '_self', '');
        window.close();

        var firefoxWarning =
        "<h1>Oops!</h1>" +
        "<h3>Firefox doesn't allow windows to self-close.</h3>" +
        "<h3>If you want the preview window to close automatically like in other browsers, go to about:config and set dom.allow_scripts_to_close_windows to true.</h3>"
        document.body.innerHTML = firefoxWarning;
      });
    });
  </script>
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="repository-with-sidebar repo-container new-discussion-timeline with-full-navigation">
        <div id="js-repo-pjax-container" class="repository-content context-loader-container">
          <div id="readme" class="boxed-group flush clearfix announce instapaper_body md">
            <article class="markdown-body"></article>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
```

**Comment by databill** [comment]
I can not call this command in vim(7.4 or even earlier version):

```
:call vimpreviewpandoc#VimPreviewPandocConvertTo("docx,html")
```

**Comment by tex** [comment]
update your plugin, that should fix #2.
#1: I cannot reproduce. Try press F12 to open developement console, there is a console and try to locate image elements (document.getElementsByTagName('img')), look at theirs path (currentSrc). For me I can see all images and their paths leads to correct place in filesystem.

**Comment by databill** [comment]
Hi tex,

3x for your update, and I will give my response after some test.

Do you mean in the dev tool which the first attachment shows? No images 
will be requested.
You can see other requests besides images in the second attachment.

**Comment by tex** [comment]
Is your problem that source text is displayed instead of image?
Does your ``` starts at the begining of line (no tab, no spaces)?

**Comment by databill** [comment]
I actually start ``` at the beginning of the line.
There is a tab is for showing the source code in markdown.

I will give the example file in another email.

**Comment by tex** [comment]
With Firefox you have to manually open static/index.html from place you installed this plugin for first time when you opened tab in Firefox. It shows empty page, but with RemoteControl plugin vim is able to "upload the document"...

**Comment by databill** [comment]
It's the problem of Firefox "**Remote Control**". The version in the Mozilla add-on repository is 1.0.1 which can not support the newest FF. 
I can not perform the bellow command.

```
telnet localhost 32000
```

When I install the newest plugin version1.2 in github(https://github.com/nneonneo/FF-Remote-Control/blob/master/remote_control-1.2-fx.xpi). The **Remote Control** works fine and I can see the dynamic result.

The localhost:8090 is not produced by **vimpreviewpandoc**, but by instant-mardown-d, another github project(https://github.com/suan/vim-instant-markdown).

This issue can be closed.
Suggestion: give the github link-page for **Remote Control** not in Mozilla.
