### ISSUE TITLE
pandoc parameters "--highlight-sytle" has no effect

### ISSUE THREAD

**Issue by databill** [tex/vimpreviewpandoc#2]
> Pandoc will automatically highlight syntax in fenced code blocks that are marked with a language name. (See [Extension: inline_code_attributes] and [Extension: fenced_code_attributes], above.) The Haskell library highlighting-kate is used for highlighting, which works in HTML, Docx, and LaTeX/PDF output. The color scheme can be selected using the --highlight-style option. The default color scheme is pygments, which imitates the default color scheme used by the Python library pygments, but pygments is not actually used to do the highlighting.
> 
> To see a list of language names that pandoc will recognize, type pandoc --version.

But in the output the html or through the web file (.vim/bundle/vimpreviewpandoc/static/index.html), we can not see the any effects.

If I use pandoc in the cli to output the html file, I can see the it works right.

``` c
for (i=1;i<10;i++)
{
    print i*i;
}
```

``` python
for i in range(5):
    print i^2
```

**Comment by tex** [comment]
This is matter of CSS style used in static/index.html which is currently very simple. And there is no direct way to reuse styles defined by pandoc in static/index.html preview.
