### ISSUE TITLE
How is the preview triggered?

### ISSUE THREAD

**Issue by gzahl** [tex/vimpreviewpandoc#6]
I have installed 
Plugin 'vim-pandoc/vim-pandoc'                                                  
Plugin 'vim-pandoc/vim-pandoc-syntax'                                           
Plugin 'vim-pandoc/vim-pandoc-after'                                            

Plugin 'prabirshrestha/async.vim'                                               
Plugin 'christianrondeau/vim-base64'                                            
Plugin 'tex/vimpreviewpandoc'                                                   
with Vundle, i can see the pandoc/markdown syntax. But the qutebrowser is not appearing.
How do i actually trigger the preview?
Qutebrowser is working fine if started manually.

Thanks for this plugin, it looks awesome and is exactly what i was looking for (pandoc preview, with auto-scrolling, minimal browser).

**Comment by tex** [comment]
Hi, try fetch latest master. Probably qutebrowser takes longer to fully initialize webview on your computer.
When you open md document, it should start qutebrowser if it is not already running. Then first tab is overtaken by vim preview and displays rendered markdown.

**Comment by gzahl** [comment]
Hi, thanks for your answer.
I won't be able to access the pc for a few days, but i have tested it on my laptop and was not able to reproduce the issue.
I will try you fix on the faulty pc, but i guess it is a problem with that specific machine.
So i guess this can be closed.
Thanks.
